// 'use client';

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import {  useAuth } from '@/app/appContexts/AuthContext'
// import { AuthProvider, AuthContext } from '@/app/appContexts/AuthContext'
const {user} = useAuth()
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <AuthProvider> */}
          {/* {children} */}
          {user}
        {/* </AuthProvider> */}
      </body>
    </html>
  )
}
